title: "Hello. I'm Gagan Shergill."
email: "gaganshergill11@gmail.com"
description: "I am a school psychologist and doctoral student whose research centers on learning analytics, artificial intelligence, and the development of equitable, data-driven approaches to support multilingual learners."
baseurl: "" 
url: "https://gagan-shergill.github.io"

github_username: "gagan-shergill"
instagram_username: "schoolpsychbytes"
linkedin_username: "gagan-shergill"

theme: jekyll-theme-cayman