{% if site.instagram_username %}
  <li>
    <a href="https://instagram.com/{{ site.instagram_username }}" target="_blank">
      <i class="fa fa-instagram"></i>
    </a>
  </li>
{% endif %}
{% if site.linkedin_username %}
  <li>
    <a href="https://www.linkedin.com/in/{{ site.linkedin_username }}" target="_blank">
      <i class="fa fa-linkedin"></i>
    </a>
  </li>
{% endif %}
